/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedSyncRouteImport } from './routes/_authenticated/sync'
import { Route as AuthenticatedStrategyRouteImport } from './routes/_authenticated/strategy'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedExchangesRouteImport } from './routes/_authenticated/exchanges'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBotRouteImport } from './routes/_authenticated/bot'
import { Route as AuthenticatedBalancesRouteImport } from './routes/_authenticated/balances'
import { Route as ApiPublicGithubWebhookRouteImport } from './routes/api/public/github/webhook'
import { Route as ApiPublicBotTransfersRouteImport } from './routes/api/public/bot/transfers'
import { Route as ApiPublicBotStatusRouteImport } from './routes/api/public/bot/status'
import { Route as ApiPublicBotIntentsRouteImport } from './routes/api/public/bot/intents'
import { Route as ApiPublicBotFillsRouteImport } from './routes/api/public/bot/fills'
import { Route as ApiPublicBotEventsRouteImport } from './routes/api/public/bot/events'
import { Route as ApiPublicBotContextRouteImport } from './routes/api/public/bot/context'
import { Route as ApiPublicBotConfigRouteImport } from './routes/api/public/bot/config'
import { Route as ApiPublicBotBalancesRouteImport } from './routes/api/public/bot/balances'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSyncRoute = AuthenticatedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategyRoute = AuthenticatedStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExchangesRoute = AuthenticatedExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotRoute = AuthenticatedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalancesRoute = AuthenticatedBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGithubWebhookRoute = ApiPublicGithubWebhookRouteImport.update({
  id: '/api/public/github/webhook',
  path: '/api/public/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotTransfersRoute = ApiPublicBotTransfersRouteImport.update({
  id: '/api/public/bot/transfers',
  path: '/api/public/bot/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotStatusRoute = ApiPublicBotStatusRouteImport.update({
  id: '/api/public/bot/status',
  path: '/api/public/bot/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotIntentsRoute = ApiPublicBotIntentsRouteImport.update({
  id: '/api/public/bot/intents',
  path: '/api/public/bot/intents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotFillsRoute = ApiPublicBotFillsRouteImport.update({
  id: '/api/public/bot/fills',
  path: '/api/public/bot/fills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotEventsRoute = ApiPublicBotEventsRouteImport.update({
  id: '/api/public/bot/events',
  path: '/api/public/bot/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotContextRoute = ApiPublicBotContextRouteImport.update({
  id: '/api/public/bot/context',
  path: '/api/public/bot/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotConfigRoute = ApiPublicBotConfigRouteImport.update({
  id: '/api/public/bot/config',
  path: '/api/public/bot/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotBalancesRoute = ApiPublicBotBalancesRouteImport.update({
  id: '/api/public/bot/balances',
  path: '/api/public/bot/balances',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balances': typeof AuthenticatedBalancesRoute
  '/bot': typeof AuthenticatedBotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchanges': typeof AuthenticatedExchangesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/strategy': typeof AuthenticatedStrategyRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/api/public/bot/balances': typeof ApiPublicBotBalancesRoute
  '/api/public/bot/config': typeof ApiPublicBotConfigRoute
  '/api/public/bot/context': typeof ApiPublicBotContextRoute
  '/api/public/bot/events': typeof ApiPublicBotEventsRoute
  '/api/public/bot/fills': typeof ApiPublicBotFillsRoute
  '/api/public/bot/intents': typeof ApiPublicBotIntentsRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
  '/api/public/bot/transfers': typeof ApiPublicBotTransfersRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balances': typeof AuthenticatedBalancesRoute
  '/bot': typeof AuthenticatedBotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchanges': typeof AuthenticatedExchangesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/strategy': typeof AuthenticatedStrategyRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/api/public/bot/balances': typeof ApiPublicBotBalancesRoute
  '/api/public/bot/config': typeof ApiPublicBotConfigRoute
  '/api/public/bot/context': typeof ApiPublicBotContextRoute
  '/api/public/bot/events': typeof ApiPublicBotEventsRoute
  '/api/public/bot/fills': typeof ApiPublicBotFillsRoute
  '/api/public/bot/intents': typeof ApiPublicBotIntentsRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
  '/api/public/bot/transfers': typeof ApiPublicBotTransfersRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/balances': typeof AuthenticatedBalancesRoute
  '/_authenticated/bot': typeof AuthenticatedBotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exchanges': typeof AuthenticatedExchangesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/strategy': typeof AuthenticatedStrategyRoute
  '/_authenticated/sync': typeof AuthenticatedSyncRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/api/public/bot/balances': typeof ApiPublicBotBalancesRoute
  '/api/public/bot/config': typeof ApiPublicBotConfigRoute
  '/api/public/bot/context': typeof ApiPublicBotContextRoute
  '/api/public/bot/events': typeof ApiPublicBotEventsRoute
  '/api/public/bot/fills': typeof ApiPublicBotFillsRoute
  '/api/public/bot/intents': typeof ApiPublicBotIntentsRoute
  '/api/public/bot/status': typeof ApiPublicBotStatusRoute
  '/api/public/bot/transfers': typeof ApiPublicBotTransfersRoute
  '/api/public/github/webhook': typeof ApiPublicGithubWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balances'
    | '/bot'
    | '/dashboard'
    | '/exchanges'
    | '/logs'
    | '/operations'
    | '/scanner'
    | '/sessions'
    | '/strategy'
    | '/sync'
    | '/trades'
    | '/transfers'
    | '/api/public/bot/balances'
    | '/api/public/bot/config'
    | '/api/public/bot/context'
    | '/api/public/bot/events'
    | '/api/public/bot/fills'
    | '/api/public/bot/intents'
    | '/api/public/bot/status'
    | '/api/public/bot/transfers'
    | '/api/public/github/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balances'
    | '/bot'
    | '/dashboard'
    | '/exchanges'
    | '/logs'
    | '/operations'
    | '/scanner'
    | '/sessions'
    | '/strategy'
    | '/sync'
    | '/trades'
    | '/transfers'
    | '/api/public/bot/balances'
    | '/api/public/bot/config'
    | '/api/public/bot/context'
    | '/api/public/bot/events'
    | '/api/public/bot/fills'
    | '/api/public/bot/intents'
    | '/api/public/bot/status'
    | '/api/public/bot/transfers'
    | '/api/public/github/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/balances'
    | '/_authenticated/bot'
    | '/_authenticated/dashboard'
    | '/_authenticated/exchanges'
    | '/_authenticated/logs'
    | '/_authenticated/operations'
    | '/_authenticated/scanner'
    | '/_authenticated/sessions'
    | '/_authenticated/strategy'
    | '/_authenticated/sync'
    | '/_authenticated/trades'
    | '/_authenticated/transfers'
    | '/api/public/bot/balances'
    | '/api/public/bot/config'
    | '/api/public/bot/context'
    | '/api/public/bot/events'
    | '/api/public/bot/fills'
    | '/api/public/bot/intents'
    | '/api/public/bot/status'
    | '/api/public/bot/transfers'
    | '/api/public/github/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBotBalancesRoute: typeof ApiPublicBotBalancesRoute
  ApiPublicBotConfigRoute: typeof ApiPublicBotConfigRoute
  ApiPublicBotContextRoute: typeof ApiPublicBotContextRoute
  ApiPublicBotEventsRoute: typeof ApiPublicBotEventsRoute
  ApiPublicBotFillsRoute: typeof ApiPublicBotFillsRoute
  ApiPublicBotIntentsRoute: typeof ApiPublicBotIntentsRoute
  ApiPublicBotStatusRoute: typeof ApiPublicBotStatusRoute
  ApiPublicBotTransfersRoute: typeof ApiPublicBotTransfersRoute
  ApiPublicGithubWebhookRoute: typeof ApiPublicGithubWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sync': {
      id: '/_authenticated/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthenticatedSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategy': {
      id: '/_authenticated/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof AuthenticatedStrategyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exchanges': {
      id: '/_authenticated/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof AuthenticatedExchangesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot': {
      id: '/_authenticated/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthenticatedBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balances': {
      id: '/_authenticated/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof AuthenticatedBalancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/github/webhook': {
      id: '/api/public/github/webhook'
      path: '/api/public/github/webhook'
      fullPath: '/api/public/github/webhook'
      preLoaderRoute: typeof ApiPublicGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/transfers': {
      id: '/api/public/bot/transfers'
      path: '/api/public/bot/transfers'
      fullPath: '/api/public/bot/transfers'
      preLoaderRoute: typeof ApiPublicBotTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/status': {
      id: '/api/public/bot/status'
      path: '/api/public/bot/status'
      fullPath: '/api/public/bot/status'
      preLoaderRoute: typeof ApiPublicBotStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/intents': {
      id: '/api/public/bot/intents'
      path: '/api/public/bot/intents'
      fullPath: '/api/public/bot/intents'
      preLoaderRoute: typeof ApiPublicBotIntentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/fills': {
      id: '/api/public/bot/fills'
      path: '/api/public/bot/fills'
      fullPath: '/api/public/bot/fills'
      preLoaderRoute: typeof ApiPublicBotFillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/events': {
      id: '/api/public/bot/events'
      path: '/api/public/bot/events'
      fullPath: '/api/public/bot/events'
      preLoaderRoute: typeof ApiPublicBotEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/context': {
      id: '/api/public/bot/context'
      path: '/api/public/bot/context'
      fullPath: '/api/public/bot/context'
      preLoaderRoute: typeof ApiPublicBotContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/config': {
      id: '/api/public/bot/config'
      path: '/api/public/bot/config'
      fullPath: '/api/public/bot/config'
      preLoaderRoute: typeof ApiPublicBotConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/balances': {
      id: '/api/public/bot/balances'
      path: '/api/public/bot/balances'
      fullPath: '/api/public/bot/balances'
      preLoaderRoute: typeof ApiPublicBotBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalancesRoute: typeof AuthenticatedBalancesRoute
  AuthenticatedBotRoute: typeof AuthenticatedBotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExchangesRoute: typeof AuthenticatedExchangesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedStrategyRoute: typeof AuthenticatedStrategyRoute
  AuthenticatedSyncRoute: typeof AuthenticatedSyncRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalancesRoute: AuthenticatedBalancesRoute,
  AuthenticatedBotRoute: AuthenticatedBotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExchangesRoute: AuthenticatedExchangesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedStrategyRoute: AuthenticatedStrategyRoute,
  AuthenticatedSyncRoute: AuthenticatedSyncRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBotBalancesRoute: ApiPublicBotBalancesRoute,
  ApiPublicBotConfigRoute: ApiPublicBotConfigRoute,
  ApiPublicBotContextRoute: ApiPublicBotContextRoute,
  ApiPublicBotEventsRoute: ApiPublicBotEventsRoute,
  ApiPublicBotFillsRoute: ApiPublicBotFillsRoute,
  ApiPublicBotIntentsRoute: ApiPublicBotIntentsRoute,
  ApiPublicBotStatusRoute: ApiPublicBotStatusRoute,
  ApiPublicBotTransfersRoute: ApiPublicBotTransfersRoute,
  ApiPublicGithubWebhookRoute: ApiPublicGithubWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
